AllCops:
  Exclude:
    - '**/Gemfile'
    - '**/*.gemspec'
    - 'pkg/**/*'

Style/RegexpLiteral:
  Exclude:
    - '**/Guardfile'

Style/Documentation:
  Exclude:
    - 'spec/**/*.rb'

Lint/UnusedMethodArgument:
  Exclude:
    - 'lib/chef_gen/snippet/*.rb'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 20
